var width = 10;
var height = 5;
var area = width * height;
console.log('value of area:', area);
console.log('typeof area:', typeof area);
var bill = 100;
var payment = 200;
var change = payment - bill;
console.log('value of change:', change);
console.log('typeof change:', typeof change);
var quizzes = 75;
var mideterm = 80;
var final = 75;
var grade = (quizzes + mideterm + final) / 3;
console.log('value of grade:', grade);
console.log('typeof grade:', typeof grade);
var firstName = 'Marley';
var lastName = 'Doughty';
var fullName = firstName + ' ' + lastName;
console.log('value of fullName:', fullName);
console.log('typeof fullName:', typeof fullName);
var pH = 5;
var isAcidic = pH < 7;
console.log('value of isAcidic:', isAcidic);
console.log('typeof isAcidic:', typeof isAcidic);
var headCount = 25;
var isSparta = headCount === 300;
console.log('value of isSparta:', isSparta);
console.log('typeof isSparta:', typeof isSparta);
var motto = fullName;
motto = fullName + ' ' + 'is the GOAT';
console.log('value of motto:', motto);
console.log('typeof motto:', typeof motto);
